# Default programs
$terminal = ghostty
$fileManager = thunar
exec-once = thunar --daemon
$menu = rofi -show drun
$windowMenu = rofi -show window
$sshMenu = rofi -show ssh -terminal $terminal -window

