hl.on("hyprland.start", function()
	hl.exec_cmd("thunar --daemon")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dunst")
	hl.exec_cmd("noctalia-shell")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("poweralertd")
	-- hl.exec_cmd("hyprlauncher -d")

	-- TODO: add check for if device is ASUS ROG device. if so exec "rog-control-center"
end)
