general {
    lock_cmd = noctalia msg session lock
    unlock_cmd = notify-send "unlock!"
    before_sleep_cmd = noctalia msg session lock
    after_sleep_cmd = noctalia msg dpms-on
}

listener {
    timeout = 300
    on-timeout = noctalia msg session lock
    on-resume = notify-send "Welcome back!"
}

listener {
    timeout = 300
    on-timeout = noctalia msg dpms-off
    on-resume = noctalia msg dpms-on
}
